[package]
authors = ["Trangar <victor.koenders@gmail.com>"]
edition = "2018"
name = "factorio_with_physics"
version = "0.1.0"

[dependencies]
noisy_float = { path = "libs/noisy_float-rs" }
itertools = "0.8"
specs = "0.15"
macros = { path = "libs/macros" }